name: Continuous Integration
on:
    # Every push
    push:
    schedule:
        # Every Monday and Thursday at 12PM UTC
        - cron: '0 12 * * 1,4'

jobs:
    test:
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]
                php-version: [ '7.1', '7.2', '7.3', '7.4' ]
        runs-on: ${{ matrix.os }}
        steps:
        - uses: actions/checkout@v2
        - uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-version }}
            coverage: xdebug
        - run: composer install
        - run: vendor/bin/phpunit --coverage-clover=coverage.xml
#        - uses: codecov/codecov-action@v1
#          with:
#            token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
